### ISSUE TITLE
passing options to the webpack compiler?

### ISSUE THREAD

**Issue by dlong500** [asfktz/autodll-webpack-plugin#1]
I'm not seeing any way to pass additional options to the webpack compiler.  Not even something as common as using the `UglifyJSPlugin`.

Because of this, the resultant file is not minified or optimized in any way and is very large.  Am I missing something or have you just not added these capabilities yet?

**Comment by d3viant0ne** [comment]
Why would you use `UglifyJSPlugin` in development?

All this does is extend the functionality of Webpacks existing DLL functionality which is limited to development & exists for the purpose of reducing rebuild cycle times. 

It's unrelated to any other plugins, less the injection via html-webpack-plugin.

**Comment by asfktz** [comment]
Hi @dlong500,

In the context of a production build, it does makes a lot of sense.

I plan to merge https://github.com/asfktz/autodll-webpack-plugin/pull/4 tomorrow, after I'll double check it.
