### ISSUE TITLE
Webpack 4 support

### ISSUE THREAD

**Issue by mhheise** [asfktz/autodll-webpack-plugin#105]
I tried upgrading to webpack 4 but I am seeing this error:

```
TypeError: compiler.applyPlugins is not a function
    at (cwd)\node_modules\autodll-webpack-plugin\lib\plugin.js:142:20
    at <anonymous>
```

Looks like the error might be from this line:

https://github.com/asfktz/autodll-webpack-plugin/blob/master/src/plugin.js#L86

```js
compiler.applyPlugins('autodll-stats-retrieved', stats, source);
```

I am not sure if you are working on this upgrade already (as webpack 4 made several breaking changes to the plugin system) -- but I would be happy to help.

**Comment by sudo-suhas** [comment]
Hey @mhheise, thanks for bringing this up! It would be very much welcome if you could make a PR with the changes required for webpack 4.

**Comment by emmenko** [comment]
I was trying to fix this issue as well, but I couldn't figure out yet what's the correct API to use here.

/cc @ooflorent @TheLarkInn Any hint on how to fix this? Also, is the "old" `compiler.plugin` API still working or does it need to be upgraded as well?
Thanks 🙏

**Comment by ooflorent** [comment]
First, you must add a custom hook the `compiler`:

```js
compiler.hooks.autodllStatsRetrieved = new SyncHooks(["stats", "source"]);
```

Then you can replace `applyPlugins` by:

```js
compiler.hooks.autodllStatsRetrieved.call(stats, source);
```

**Comment by emmenko** [comment]
@ooflorent many thanks!

@sudo-suhas would you like to take care of this? Otherwise I'll try to open a PR.
It would be good to have webpack@4 support soon ;)

**Comment by mhheise** [comment]
I have started work on my own fork -- I can push it up for review soon once tests are passing 😄

**Comment by emmenko** [comment]
@mhheise awesome! 🙌

**Comment by mhheise** [comment]
@asfktz @sudo-suhas I have changes underway and will push a WIP PR shortly, but I am seeing this error when I am testing my changes with the examples directory:

```bash
Error: ENOENT: no such file or directory, open 'C:\Git\autodll-webpack-plugin\examples\recommended\node_modules\.cache\autodll-webpack-plugin\development_instance_0_1dc0c813842ea3b964c005e53b6b3ea3\vendor.manifest.json'
```

Any thoughts? I know that the file is not present on my machine, but I am not quite sure how to generate it so that an `npm run build` would succeed.

**Comment by asfktz** [comment]
Hi @mhheise!

First, thanks a lot for taking this  🙏

I'll take a look at it tomorrow and see what I can do to help (:

**Comment by asfktz** [comment]
Hi @mhheise, I've left I few notes in the PR

**Comment by marcofugaro** [comment]
Any update on this? `html-webpack-plugin` has been upgraded

**Comment by faceyspacey** [comment]
I got html-webpack-plugin working. Please verify so it can get merged to the main package sooner:

https://www.npmjs.com/package/autodll-webpack-plugin-webpack-4
`yarn add --dev autodll-webpack-plugin-webpack-4`

**Comment by simonjoom** [comment]
Just found a little bug in version 4 of webpack . On first run (without nothing in cache .cache) 
The compilation stop processing to next step a callback is never called...

is just added some return in watchrun did the trick for me
var watchRun = function watchRun(compiler, callback) {
        compileIfNeeded(function () {
          return (0, _webpack2.default)(dllConfig);
        }).then(function (a) {
          return a;
        }).then(handleStats).then(function (_ref) {
          var source = _ref.source,
              stats = _ref.stats;
          if (compiler.hooks) {
  here  ->        return compiler.hooks.autodllStatsRetrieved = new _tapable.SyncHook(['stats', 'source']);
  here  ->        return compiler.hooks.autodllStatsRetrieved.call(stats, source);
          } else {
            return compiler.applyPlugins('autodll-stats-retrieved', stats, source);
          }

**Comment by imjeen** [comment]
@faceyspacey There is a little problem about the `autodll-webpack-plugin-webpack-4` plugin.

 `npm i -S autodll-webpack-plugin-webpack-4` and  build with the plugin, it's error. 

Maybe you can try with a new demo.  (do not install `autodll-webpack-plugin` and use it )

**Comment by asfktz** [comment]
Hi everybody,
A new version released with webpack 4 support.

Thanks for @mhheise & @faceyspacey for making it happen ❤️

**Comment by mlippens** [comment]
Can't this be closed then? :+1:
