### ISSUE TITLE
branch webpack 4 little bug for first run resolved

### ISSUE THREAD

**Issue by simonjoom** [asfktz/autodll-webpack-plugin#113]
Just found a little bug in version 4 of webpack . On first run (without nothing in cache .cache) 
The compilation stop processing to next step a callback is never called...

**Comment by simonjoom** [comment]
Sorry the code is good finally;... it was my mistake you should to close it 
don't matter about that

**Comment by asfktz** [comment]
A new version released with webpack 4 support
