### ISSUE TITLE
Example cannot be run with node 4

### ISSUE THREAD

**Issue by sudo-suhas** [asfktz/autodll-webpack-plugin#16]
If I try to run the recommended example with node 4, the following happens:
```
λ npm install
npm WARN package.json basic@1.0.0 No description
npm WARN package.json basic@1.0.0 No repository field.
npm WARN package.json basic@1.0.0 No README data
npm WARN unmet dependency E:\Projects\repos\autodll-webpack-plugin\examples\recommended\node_modules\html-webpack-plugin\node_modules\pretty-error\node_modules\renderkid requires utila@'~0.3' but will load
npm WARN unmet dependency E:\Projects\repos\autodll-webpack-plugin\examples\recommended\node_modules\html-webpack-plugin\node_modules\pretty-error\node_modules\utila,
npm WARN unmet dependency which is version 0.4.0
npm WARN unmet dependency E:\Projects\repos\autodll-webpack-plugin\examples\recommended\node_modules\webpack-dev-server\node_modules\http-proxy-middleware\node_modules\micromatch requires is-glob@'^2.0.1' but will load
npm WARN unmet dependency E:\Projects\repos\autodll-webpack-plugin\examples\recommended\node_modules\webpack-dev-server\node_modules\http-proxy-middleware\node_modules\is-glob,
npm WARN unmet dependency which is version 3.1.0
npm ERR! Windows_NT 6.2.9200
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v4.8.0
npm ERR! npm  v2.15.11
npm ERR! code EPEERINVALID

npm ERR! peerinvalid The package webpack@3.0.0 does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer html-webpack-plugin@2.29.0 wants webpack@1 || ^2 || ^2.1.0-beta || ^2.2.0-rc || ^3
npm ERR! peerinvalid Peer webpack-dev-server@2.5.0 wants webpack@^2.2.0
```

I don't think this is a big deal but maybe mention the compatible node version in the readme? You could also include a `engines` key in `package.json` like so:
```js
{
  // ...
  "engines": {
    "node": ">= 6.9.2",
    "npm": ">= 3.10.9"
  },
}
```

**Comment by sudo-suhas** [comment]
Sorry.. Closed the wrong one

**Comment by GrimDev** [comment]
Hi !
Same kind of problem in node 4.2.4 that doesn't support ES2015 destructuring apparently used in this module.
Got a SyntaxError in the file : plugin.js (let { entry } = _ref).

I will upgrade my nodejs soon to fix this problem but it would have been nicer if the lowest supported node version had been written in the README or appears in package.json.
Could you please explicit the compatibility somewhere ?

Thanks you.

**Comment by sudo-suhas** [comment]
@GrimDev As it happens, this issue of not being to use the module with node v4 was identified(#17) and fixed(#19) already. However, due to an oversight, the package version `0.0.8` was not published to npm. I have created an issue for the same - #29. It should be resolved soon. But you are quite right, the compatibility should be explicitly mentioned.

**Comment by asfktz** [comment]
@sudo-suhas is it still relevant?

**Comment by sudo-suhas** [comment]
I was able to run the example on node `v4.8.0`. Closing.
