### ISSUE TITLE
Examples use older version of lib

### ISSUE THREAD

**Issue by sudo-suhas** [asfktz/autodll-webpack-plugin#20]
For example:
https://github.com/asfktz/autodll-webpack-plugin/blob/master/examples/recommended/package.json#L11

This can be used either with `"autodll-webpack-plugin": "latest"` or `"autodll-webpack-plugin": "file:../../"` as used in the [minification exmaple](https://github.com/asfktz/autodll-webpack-plugin/blob/master/examples/minification/package.json#L10). 

Personally, I feel using a latest published version in the examples might be better. But using the file version would handle API changes(if any, in the future) better.

**Comment by asfktz** [comment]
I prefer `latest` because as a user it might be confusing to try to run the examples and see them fails if you don't know that you must build the project first.

In the contribution guide, we can explain that it is possible to test the examples using `npm link`

What do you think?

**Comment by sudo-suhas** [comment]
@asfktz that sounds perfect.

**Comment by asfktz** [comment]
done.
