### ISSUE TITLE
Watch for changes to files / package.json

### ISSUE THREAD

**Issue by ankit** [asfktz/autodll-webpack-plugin#22]
I am currently using https://github.com/shlomiassaf/webpack-dll-bundles-plugin which looks for changes to `package.json` in node modules to recompile the dlls, which is really useful if the node module gets updated.

With that plugin, I am also doing a hack, where I have added a `package.json` to local code in order to pull out local library code (until it is moved out into its own npm package).

I was wondering if it would be possible for this plugin to:

- Watch package.json of node modules to invalidate the dll cache 
- Watch changes to any files referenced in the dll to invalidate the cache

**Comment by asfktz** [comment]
Hi, @ankit 

We are currently working on adding watch mode to the Plugin.
I agree with you that It is much needed.

**Comment by ankit** [comment]
Ah just noticed #7! thanks @asfktz. Closing this issue.
