### ISSUE TITLE
package version 0.0.8 not published on npm

### ISSUE THREAD

**Issue by sudo-suhas** [asfktz/autodll-webpack-plugin#29]
The package version available on npm is still `0.0.7`.

[`v0.0.7` vs `0.0.8`](https://github.com/asfktz/autodll-webpack-plugin/compare/6b58ca0addfc8426c3f6c035a9f666f222ad8c7f...33482a00c00248ee4558879f40da1be19c1666cc)

As you can see, there are important bug fixes not yet published. Please publish at the earliest.

Link - https://www.npmjs.com/package/autodll-webpack-plugin

**Comment by asfktz** [comment]
Oghhh..! I forgot to hit publish. done.

Thanks again @sudo-suhas
