### ISSUE TITLE
Add e2e tests: Treat examples like a fixture?

### ISSUE THREAD

**Issue by viankakrisna** [asfktz/autodll-webpack-plugin#31]
And write tests for it.

This is beneficial to find regression / developing a new feature.

Right now we only have spec for the units but not for the use cases

**Comment by viankakrisna** [comment]
To avoid issue like https://github.com/asfktz/autodll-webpack-plugin/issues/21

**Comment by asfktz** [comment]
I'm not familiar with fixtures, but it sounds exactly like what I was looking for.

Can you please tell me more about it?

**Comment by viankakrisna** [comment]
Taken from [here](https://github.com/junit-team/junit4/wiki/test-fixtures)
>A test fixture is a fixed state of a set of objects used as a baseline for running tests. The purpose of a test fixture is to ensure that there is a well known and fixed environment in which tests are run so that results are repeatable.

**Comment by viankakrisna** [comment]
I'm also a new to this testing world (haven't yet set it up from scratch), so I hope I don't use the wrong terms here 😅  Basically it's a file/set of file that we run our test for, to test multiple real world scenario.

**Comment by asfktz** [comment]
Looks like something I need to dive into 😄 
Will do.

**Comment by viankakrisna** [comment]
I think this looks more like an e2e test, I don't know if we should use examples as fixtures or written it separately. The test looks like this https://github.com/viankakrisna/autodll-webpack-plugin/blob/1d5979f96a556764fd862410110814beb2e7643f/specs/features.spec.js

**Comment by viankakrisna** [comment]
Possible e2e cases to be added:

Integration with other webpack plugins:
- SWPrecache
- ManifestPlugin
- ExtractTextPlugin
This is what commonly used plugins, at least, it used in CRA. If we can write tests and manage compatibility with it, surely it would boost the confidence level to be used in it :)

**Comment by asfktz** [comment]
I started to work on it.
This article looks interesting:  https://blog.iansinnott.com/testing-webpack-plugins/

**Comment by viankakrisna** [comment]
Great! thanks for sharing it 👍

**Comment by asfktz** [comment]
Of Course (:

**Comment by asfktz** [comment]
Done! Thanks for convincing me to add it @viankakrisna, it turns out to be very useful.
