### ISSUE TITLE
Seems conflict with VueSSRServerPlugin

### ISSUE THREAD

**Issue by xekri** [asfktz/autodll-webpack-plugin#55]
My server side rendering webpack config is below. When created `vue-ssr-server-bundle.json`, it doesn't use dll vendor file.
When I commented out the `VueSSRServerPlugin`, it seems work fine. I believe there's a conflict with VueSSRServerPlugin, would any one check it? Thx.
PS. use original dll plugin, it works as expected.
```
module.exports = merge(baseConfig, {
  target: 'node',
  output: {
    libraryTarget: 'commonjs2'
  },
  externals: nodeExternals({
    // do not externalize CSS files in case we need to import it from a dep
    whitelist: /\.css$/
  }),
  plugins: [
    new AutoDllPlugin({
      debug: true,
      inject: false,
      filename: 'server.dll.[hash].js',
      context: PATH.ROOT,
      entry: {
        vendor: [
          'vue',
          'vue-router'
        ]
      }
    }),
    new webpack.DefinePlugin({
      'process.env.VUE_ENV': '"server"'
    }),
    new VueSSRServerPlugin()
  ]
})
```

**Comment by freeozyl80** [comment]
you mean DllReferencePlugin can work fine with VueSSRServerPlugin ?

**Comment by xekri** [comment]
@freeozyl80 Seems fine to me.

**Comment by xekri** [comment]
@freeozyl80 Sorry, I looked into it and found it's not a good choice to use VueSSRServerPlugin with any kind of Dll plugins of webpack. It will certainly destroy the client-manifest file so that some async scripts won't be loaded corretly.

**Comment by tryggvigy** [comment]
@xekri Was this issue resolved? If so, it would be great if you could close it! 🙂
