### ISSUE TITLE
 Entry point name is not recognized as a directory

### ISSUE THREAD

**Issue by km-tr** [asfktz/autodll-webpack-plugin#56]
```js
new AutoDllPlugin({
    debug: true,
    filename: '[name].dll.bundle.js',
    entry: {
      'citizen/sp': ['react', 'react-dom'],
    },
  }),
```

If it is an entry point of webpack, the slash delimiter is recognized as a directory at the output destination, but is not this plugin supported?

**Comment by asfktz** [comment]
Hi, @km-tr!
Welcome (:

I believe it's related to the DllPlugin itself since the `entry` option is passed to it as is.

Also the same for https://github.com/asfktz/autodll-webpack-plugin/issues/57
