### ISSUE TITLE
How to use with html-webpack-template?

### ISSUE THREAD

**Issue by EvgenyOrekhov** [asfktz/autodll-webpack-plugin#59]
[HTML Webpack Template](https://github.com/jaketrent/html-webpack-template) requires setting html-webpack-plugin's `inject` option to `false`, so when I do

```js
    plugins: [
        new HtmlWebpackPlugin({
            template: HtmlWebpackTemplate,
            inject: false
        }),
        new AutoDllWebpackPlugin({
            inject: true,
            entry: {
                vendor: [
                    "react"
                ]
            }
        })
    ]
```

the generated `index.html` is missing the `<script>` tag for `vendor.js`.

**Comment by TreeVie** [comment]
```
new HtmlWebpackPlugin({
            template: HtmlWebpackTemplate,
            inject: true
        }),
```

**Comment by EvgenyOrekhov** [comment]
@TreeVie That way I get duplicate entries of `bundle.min.css` and `bundle.min.js` in my `index.html`.

**Comment by EvgenyOrekhov** [comment]
I don't care anymore since I switched to [Parcel](https://github.com/parcel-bundler/parcel).
