### ISSUE TITLE
Is it possible to set path as an abosulte path?

### ISSUE THREAD

**Issue by vagusX** [asfktz/autodll-webpack-plugin#6]
I use `recommend` examples, using `webpack-dev-server --history-api-fallback --config ./webpack.config.js` to run local dev env, and I found that 
* in path `http://localhost:8080/123`, `http://localhost:8080/dll/vendor_8e0afce396bf5cfa4447.js` is accessible
* in path `http://localhost:8080/123/123` , `http://localhost:8080/dll/vendor_8e0afce396bf5cfa4447.js` is not accessible

webpack config here:

```js
const webpack = require('webpack');
const path = require('path');
const AutoDllPlugin = require('autodll-webpack-plugin');
const HtmlWebpackPlugin = require('html-webpack-plugin');

module.exports = {
  entry: './src/index.js',

  output: {
    filename: '[name].bundle.js',
    path: path.resolve(__dirname, 'dist'),
    publicPath: '/'
  },

  plugins: [
    new HtmlWebpackPlugin({
      inject: true,
      template: './src/index.html',
    }),
    new AutoDllPlugin({
      inject: true,
      context: __dirname,
      filename: '[name]_[hash].js',
      path: './dll',
      entry: {
        vendor: [
          'react',
          'react-dom',
          'moment'
        ]
      }
    })
  ]
};

```

**Comment by asfktz** [comment]
Interesting! I'll check it.

In the meantime, try to change `./dll`' to `/dll`, tell me if it helps.

**Comment by vagusX** [comment]
I changed `./dll` to `/dll`, and 
![screen shot 2017-07-03 at 2 10 46 pm](https://user-images.githubusercontent.com/6828924/27780084-8495feb8-5ff9-11e7-86ea-51605ff9e01b.png)

**Comment by OneCyrus** [comment]
same problem here. HtmlWebpackPlugin injects the following:
`<script type="text/javascript" src="vendor_121c4bd3d86e7db99c76.js"></script><script type="text/javascript" src="/main.bundle.js"></script></body>`

the autodll-bundle with relative path and the main webpack bundle with an absolute path.

**Comment by asfktz** [comment]
I see. Ok, I'll fix it.

**Comment by vagusX** [comment]
@asfktz  maybe here (https://github.com/asfktz/autodll-webpack-plugin/blob/master/src/plugin.js#L38) should concat with `output.pulbicPath` from `context.options`?

**Comment by asfktz** [comment]
Apologies for the slow respond, real life got too busy in the last few days.

> maybe here (https://github.com/asfktz/autodll-webpack-plugin/blob/master/src/plugin.js#L38) should concat with output.pulbicPath from context.options?

Thanks for pointing out @vagusX, I plan to fix it later today.

**Comment by asfktz** [comment]
Done.

Thank you for opening this issue, @vagusX.
It was a critical bug to fix.

**Comment by vagusX** [comment]
@asfktz  You are welcome, I think this plugin would be pretty helpful 👍

**Comment by chj-damon** [comment]
@asfktz what if the publicPath is an URL like 'http://localhost:8080/'. I found that autoDllPlugin won't work because in the index.html the path is "http:\localhost:8080\vendor_3b7540be52d24bb3523e.js". So the error is vendor_3b7540be52d24bb3523e.js is not defined.
is there anything I was wrong with the configuration?

**Comment by asfktz** [comment]
Hi, @chj-damon 
Interesting, I'll give it a look.

reopen for now.

**Comment by panuruj** [comment]
I'm seeing the same issue with the backslash instead of the forward-slash as well on Windows environment.

**Comment by tryggvigy** [comment]
@chj-damon I have opened a PR addressing this issue https://github.com/asfktz/autodll-webpack-plugin/pull/64
