### ISSUE TITLE
publicPath without http or https

### ISSUE THREAD

**Issue by AliasT** [asfktz/autodll-webpack-plugin#61]
when i set the publicPath without http or https, just like `//s.bar.com/public`,
`path.join` will make the final script tag src starts with `/s.bar.com/public` ,

[https://github.com/asfktz/autodll-webpack-plugin/blob/v0.2.1/src/paths.js#L12](https://github.com/asfktz/autodll-webpack-plugin/blob/v0.2.1/src/paths.js#L12)

**Comment by panuruj** [comment]
Also, on Windows, the final path becomes backslashes instead of a slash.
publicPath: https://localhost/
result: https:\\localhost\vendor.js

**Comment by tryggvigy** [comment]
@AliasT I opened a PR addressing this issue. https://github.com/asfktz/autodll-webpack-plugin/pull/64

**Comment by tryggvigy** [comment]
@panuruj Since you have full control over webpack's `publicPath` and autodll-webpack-plugin's `path` keys. Can't you make sure they are valid URL fragments (only `/` delimiters and no `\`)? I think `autodll-webpack-plugin` will handle that correctly.

**Comment by tryggvigy** [comment]
Oh never mind! `path.join` on windows joins with a `\`, right? So it would be a problem on windows.

**Comment by asfktz** [comment]
Hi, @AliasT!

I released a new version (`0.3.2`) which should fix it.

Can you verify that the issue resolved? Thanks
