### ISSUE TITLE
Merge into DLL Plugin?

### ISSUE THREAD

**Issue by dmitriid** [asfktz/autodll-webpack-plugin#63]
Quoting the README

> While the DllPlugin has many advantages, it's main drawback is that it requires a lot of boilerplate.
> hides away most of their complexity.
> commonly accomplished
> such a common task

etc.

The webpack site currently lists 26 different plugins. Autodll isn't there, so it will be at least 27th. Adding yet another layer of complexity to an already largely incomprehensible system.

From the quotes above it is apparent that the facilities this plugin provides are great and greatly needed. So it begs the obvious question: why not merge these into DLL Plugin as defaults? This way a developer wouldn't need to search for a yet another plugin or wade through complex configuration to accomplish common tasks.

UPD: Even though webpack site lists 26 plugins there are potentially many more. For example, DLLReferencePlugin is not listed, but exists. Its documentation is inside DLLPlugin

**Comment by asfktz** [comment]
Hi, @dmitriid 
Apologize for the like response.

It's a good question.
I tried to speak with webpack about it but got no clear answer.
DLL or not, the ability to specify a list of modules to precompile is very useful and greatly speed up the build time. I can only hope something like this will find its way to the core.
