### ISSUE TITLE
PUBLIC_URL issue

### ISSUE THREAD

**Issue by raymondsze** [asfktz/autodll-webpack-plugin#66]
https://github.com/asfktz/autodll-webpack-plugin/blob/master/src/plugin.js#L107

settings.publicPath could be something like `https://xxxx.com`
If using path.join, the `https://xxxx.com` would become `https:/xxx.com` which is incorrect.

**Comment by tryggvigy** [comment]
Hey @raymondsze! 
We have a open PR for this issue https://github.com/asfktz/autodll-webpack-plugin/pull/64

**Comment by raymondsze** [comment]
Sorry, let me close it.
