### ISSUE TITLE
Adding prettier to the codebase

### ISSUE THREAD

**Issue by Nargonath** [asfktz/autodll-webpack-plugin#72]
What do you think of formatting the codebase using prettier and adding a precommit hook to format the code? Here is the prettier config list I like to use in projects, tell me what you think about it:
* printWidth: 100
* tabWidth: 2
* useTabs: false
* semi: true
* singleQuote: true
* trailingComma: es5 (or 'all' if you want)
* bracketSpacing: true

Some of these options are prettier defaults but I listed them anyway for clarity sake.

If you are ok with it, I'll a PR to make this work.

**Comment by asfktz** [comment]
Hi, my friend, how are you? (:

Sounds good, I used prettier across the codebase, with a similar setup (configured globally in my editor), So I believe most of the files will stay the same.
And this config looks good to me, so yeah, go for it 👍

**Comment by Nargonath** [comment]
Hey! I'm doing good and you? Long time no chat it seems. :)

I'll work on it. I was wondering shall I still work on the next branch or is the master branch up-to-date now? Or perhaps the next branch is like a dev branch, isn't it?

**Comment by asfktz** [comment]
> I was wondering shall I still work on the next branch or is the master branch up-to-date now?

Yep, it's up to date now.

> Or perhaps the next branch is like a dev branch, isn't it?

Hmm.. right now the `next` branch is still there because I forgot to delete it.
Currently, I make changes directly to the master, but I'm open to suggestions.

**Comment by Nargonath** [comment]
Oh ok, cool. I'll just work on master as well then. :+1:
