### ISSUE TITLE
Adding a chat room to the repo

### ISSUE THREAD

**Issue by Nargonath** [asfktz/autodll-webpack-plugin#77]
Hello again!

As I started to get into the project more and more, I felt like it would be good to have a place where we can discuss things about the project. It would be something that everyone could join and read so emailing each other would be a no-go. What do you think?

If you are ok with it, I'll take care of it. I thought of using Gitter for that. It felt like it would be the right tool for the job.

**Comment by asfktz** [comment]
Hi @Nargonath 
Sound good! 👍 👍

**Comment by Nargonath** [comment]
@asfktz it seems I cannot create a Gitter community and link it to this repository as I'm not the owner. Do you mind creating the community please? Here is the link to do so: https://gitter.im/home#createcommunity. Once you did I'll add the relevant information on the README.md. :+1:

**Comment by asfktz** [comment]
Done! 🎉🎉 
I'm online, ping me when your there

**Comment by Nargonath** [comment]
Great! I see you added the badge as well. That's nice.
